### ISSUE TITLE
No config.yaml file

### ISSUE THREAD

**Issue by pangrunqi** [zycXD/FV-UPatches#1]
When I run this code, I cannot find the config.yaml file. It seems about the dataset. Could you share this file?

**Comment by ziyannchen** [comment]
Hi, thanks for reaching out. We've provided the download links in the README file of the homepage. You can check it out on [**Google Drive**](https://drive.google.com/drive/folders/1DmJAnlWKMup1ti9UBTZgA6qKEW6Ehtsk?usp=sharing) | [**Baidu Cloud**](https://pan.baidu.com/s/1md6Fiv6AQLD2PsCZtekthA?pwd=bkfn).
