### ISSUE TITLE
datasets

### ISSUE THREAD

**Issue by ZHENGAWU666** [zycXD/FV-UPatches#2]
通过预处理得到的软标签，代码中，没有提及如何制作软标签，请问是否可以提供一下

**Comment by ziyannchen** [comment]
您好，文中提到的软标签是通过一个基于图像二阶矩的算法生成的，由于该算法是使用matlab实现的，且后续将继续完善，因此尚未公开。
标签文件会在后续（这两个月）公开，可以关注下仓库更新。

**Comment by cy7022** [comment]
您好，文中对SDUMLA数据集进行预处理得到ROI区域，代码中并未提及具体的处理方法，请问是否可以提供一下呢？

**Comment by ZHENGAWU666** [comment]
> 您好，文中提到的软标签是通过一个基于图像二阶矩的算法生成的，由于该算法是使用matlab实现的，且后续将继续完善，因此尚未公开。 标签文件会在后续（这两个月）公开，可以关注下仓库更新。

好的，感谢回复，会继续关注
